# Generated by Django 5.2.8 on 2025-12-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_used'], name='email_verif_email_59a003_idx'), models.Index(fields=['code'], name='email_verif_code_2d0f52_idx')],
            },
        ),
    ]
