# Generated by Django 5.2.8 on 2026-01-19 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0, help_text='For future priority-based systems')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('enrolled', 'Enrolled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='api.batch')),
                ('student', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitlists',
                'ordering': ['position', 'joined_date'],
                'indexes': [models.Index(fields=['batch', 'status'], name='waitlists_batch_i_95ee00_idx'), models.Index(fields=['student', 'status'], name='waitlists_student_93f91b_idx'), models.Index(fields=['position'], name='waitlists_positio_3466e0_idx')],
                'unique_together': {('student', 'batch')},
            },
        ),
    ]
