# Generated by Django 5.2.8 on 2026-01-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite_enforcement',
            field=models.CharField(choices=[('strict', 'Strict - Must complete all prerequisites'), ('soft', 'Soft - Show warning only'), ('none', 'None - No enforcement')], default='strict', help_text='How strictly to enforce prerequisites', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Courses that must be completed before enrolling in this course', related_name='required_for', to='api.course'),
        ),
    ]
