# Generated by Django 5.2.8 on 2026-01-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_course_prerequisite_enforcement_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule_conflict_checking',
            field=models.CharField(choices=[('strict', 'Strict - Block conflicting enrollments'), ('warning', 'Warning - Show conflict but allow enrollment'), ('none', 'None - No conflict checking')], default='strict', help_text='How to handle schedule conflicts', max_length=10),
        ),
    ]
