# Generated by Django 5.2.8 on 2026-01-19 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_course_schedule_conflict_checking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('student', 'Student Import'), ('enrollment', 'Enrollment Import')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('import_results', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['import_type', 'created_at'], name='import_hist_import__373139_idx'), models.Index(fields=['imported_by', 'created_at'], name='import_hist_importe_3e35d4_idx')],
            },
        ),
    ]
