# Generated by Django 5.2.8 on 2026-01-19 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_importhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scholarship_type', models.CharField(choices=[('full', 'Full Scholarship'), ('partial', 'Partial Scholarship'), ('percentage', 'Percentage Discount')], max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scholarships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_installments', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='api.enrollment')),
            ],
            options={
                'db_table': 'payment_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.payment')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='api.paymentplan')),
            ],
            options={
                'db_table': 'installments',
                'ordering': ['installment_number'],
                'indexes': [models.Index(fields=['payment_plan', 'status'], name='installment_payment_5d0c0c_idx'), models.Index(fields=['due_date', 'status'], name='installment_due_dat_384ccd_idx')],
                'unique_together': {('payment_plan', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('application_reason', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enrollment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scholarships', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scholarship_applications',
                'ordering': ['-application_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='scholarship_student_179bda_idx'), models.Index(fields=['scholarship', 'status'], name='scholarship_scholar_4e763b_idx')],
            },
        ),
    ]
